pub static DEFAULT_PRINT: bool = true;
pub static BR: &str = "\n";
pub static COLON_SPACE: &str = ": ";
pub static COLON_SPACE_SYMBOL: &str = ":";
pub static DEFAULT_HOST: &str = "0.0.0.0";
pub static DEFAULT_WEB_PORT: usize = 80;
pub static SPLIT_REQUEST: &str = "\r\n\r\n";
pub static SPLIT_REQUEST_BYTES: &[u8] = SPLIT_REQUEST.as_bytes();
pub static DEFAULT_BUFFER_SIZE: usize = 512_000;
